cadena=input("Ingrese una cadena de texto: ")
print("La cadena es ",cadena)
print("Los dos primeros caracteres ",cadena[:2])
print("Los dos últimos caracteres ",cadena[len(cadena)-2:])
print("Todos los caracteres menos el primero y el último ",cadena[1:len(cadena)-1])
